const options = [
  { fullName: "Australia", code: "AU" },
  { fullName: "United States", code: "US" },
  { fullName: "United Kingdom", code: "UK" },
  { fullName: "Lebanon", code: "LB" },
  { fullName: "Saudi Arabia", code: "SA" },
  { fullName: "Qatar", code: "QA" },
  { fullName: "Spain", code: "ES" },
  { fullName: "Turkey", code: "TR" },
  { fullName: "Kuwait", code: "KU" },
  { fullName: "Japan", code: "JP" },
  { fullName: "Iran", code: "IR" },
  { fullName: "Italy", code: "IT" },
  { fullName: "France", code: "FR" },
  { fullName: "Canada", code: "CA" },
  { fullName: "Germany", code: "DE" },
  { fullName: "Portugal", code: "PO" },
  { fullName: "Egypt", code: "EG" },
  { fullName: "Indonesia", code: "ID" },
  { fullName: "China", code: "CN" },
  { fullName: "Russia", code: "RU" },
  { fullName: "South Africa", code: "ZA" },
  { fullName: "Argentina", code: "AR" },
  { fullName: "India", code: "IN" },
  { fullName: "Brazil", code: "BR" },
  { fullName: "Nigeria", code: "NG" },
  { fullName: "Mexico", code: "MX" },
];

export default options;
