const options = [
  { fullName: "Albania", code: "AL" },
  { fullName: "Algeria", code: "DZ" },
  { fullName: "Andorra", code: "AD" },
  { fullName: "Angola", code: "AO" },
  { fullName: "Argentina", code: "AR" },
  { fullName: "Armenia", code: "AM" },
  { fullName: "Australia", code: "AU" },
  { fullName: "Austria", code: "AT" },
  { fullName: "Azerbaijan", code: "AZ" },
  { fullName: "Bahrain", code: "BH" },
  { fullName: "Bangladesh", code: "BD" },
  { fullName: "Belarus", code: "BY" },
  { fullName: "Belgium", code: "BE" },
  { fullName: "Benin", code: "BJ" },
  { fullName: "Bolivia", code: "BO" },
  { fullName: "Botswana", code: "BW" },
  { fullName: "Brazil", code: "BR" },
  { fullName: "Bulgaria", code: "BG" },
  { fullName: "Burkina Faso", code: "BF" },
  { fullName: "Cabo Verde", code: "CV" },
  { fullName: "Cambodia", code: "KH" },
  { fullName: "Cameroon", code: "CM" },
  { fullName: "Canada", code: "CA" },
  { fullName: "Chad", code: "TD" },
  { fullName: "Chile", code: "CL" },
  { fullName: "China", code: "CN" },
  { fullName: "Colombia", code: "CO" },
  { fullName: "Comoros", code: "KM" },
  { fullName: "Costa Rica", code: "CR" },
  { fullName: "Croatia", code: "HR" },
  { fullName: "Cyprus", code: "CY" },
  { fullName: "Czech Republic", code: "CZ" },
  { fullName: "Denmark", code: "DK" },
  { fullName: "Djibouti", code: "DJ" },
  { fullName: "Ecuador", code: "EC" },
  { fullName: "Egypt", code: "EG" },
  { fullName: "El Salvador", code: "SV" },
  { fullName: "Estonia", code: "EE" },
  { fullName: "Eswatini", code: "SZ" },
  { fullName: "Ethiopia", code: "ET" },
  { fullName: "Fiji", code: "FJ" },
  { fullName: "Finland", code: "FI" },
  { fullName: "France", code: "FR" },
  { fullName: "Gabon", code: "GA" },
  { fullName: "Gambia", code: "GM" },
  { fullName: "Canada", code: "CA" },
  { fullName: "Georgia", code: "GE" },
  { fullName: "Germany", code: "DE" },
  { fullName: "Ghana", code: "GH" },
  { fullName: "Greece", code: "GR" },
  { fullName: "Guatemala", code: "GT" },
  { fullName: "Guinea", code: "GN" },
  { fullName: "Guyana", code: "GY" },
  { fullName: "Haiti", code: "HT" },
  { fullName: "Honduras", code: "HN" },
  { fullName: "Hungary", code: "HU" },
  { fullName: "Iceland", code: "IS" },
  { fullName: "India", code: "IN" },
  { fullName: "Indonesia", code: "ID" },
  { fullName: "Iran", code: "IR" },
  { fullName: "Iraq", code: "IQ" },
  { fullName: "Ireland", code: "IE" },
  { fullName: "Israel", code: "IL" },
  { fullName: "Italy", code: "IT" },
  { fullName: "Jamaica", code: "JM" },
  { fullName: "Japan", code: "JP" },
  { fullName: "Jordan", code: "JO" },
  { fullName: "Kazakhstan", code: "KZ" },
  { fullName: "Kenya", code: "KE" },
  { fullName: "Kuwait", code: "KW" },
  { fullName: "Kyrgyzstan", code: "KG" },
  { fullName: "Laos", code: "LA" },
  { fullName: "Latvia", code: "LV" },
  { fullName: "Lebanon", code: "LB" },
  { fullName: "Lesotho", code: "LS" },
  { fullName: "Liberia", code: "LR" },
  { fullName: "Libya", code: "LY" },
  { fullName: "Liechtenstein", code: "LI" },
  { fullName: "Lithuania", code: "LT" },
  { fullName: "Luxembourg", code: "LU" },
  { fullName: "Madagascar", code: "MG" },
  { fullName: "Nigeria", code: "NG" },
  { fullName: "Portugal", code: "PO" },
  { fullName: "Russia", code: "RU" },
  { fullName: "Saudi Arabia", code: "SA" },
  { fullName: "South Africa", code: "ZA" },
  { fullName: "Spain", code: "ES" },
  { fullName: "United Kingdom", code: "UK" },
  { fullName: "United States", code: "US" },
  { fullName: "Uruguay", code: "UY" },
];

export default options;
